DATA_PATH = "data"
MODEL_PATH = "model"

DEFAULT_TRAINING_FILE = f"{DATA_PATH}/animelist.csv"
DEFAULT_COLUMNS_TO_READ = ["user_id", "anime_id", "rating"]
DEFAULT_NUM_ROWS_TO_FETCH = -1
DEFAULT_LOW_MEMORY_MODE = False

DEFAULT_SAMPLE_FRACTION = 0.005
DEFAULT_SAMPLE_RANDOM_STATE = 1

DEFAULT_EPOCH_COUNT = 3